server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Para React Router: cualquier path que no sea un archivo real
        # retorna index.html y React maneja el routing del lado del cliente.
        try_files $uri $uri/ /index.html; 
    }
}