services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - donaton-network
    depends_on:
      - bff

  bff:
    build: ./backend/bff
    container_name: bff
    ports:
      - "8080:8080"
    networks:
      - donaton-network
    depends_on:
      - ms-auth
      - ms-profile
      - ms-donation
      - ms-inventory
      - ms-logistic
    environment:
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - SERVICES_AUTH_URL=http://ms-auth:8081
      - SERVICES_PROFILE_URL=http://ms-profile:8082
      - SERVICES_DONATIONS_URL=http://ms-donation:8083
      - SERVICES_INVENTORY_URL=http://ms-inventory:8084
      - SERVICES_LOGISTIC_URL=http://ms-logistic:8085

  ms-auth:
    build: ./backend/ms-auth
    container_name: ms-auth
    ports:
      - "8081:8081"
    networks:
      - donaton-network
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  ms-profile:
    build: ./backend/ms-profile
    container_name: ms-profile
    networks:
      - donaton-network
    depends_on:
      profile-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://profile-db:5432/profile-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  ms-donation:
    build: ./backend/ms-donation
    container_name: ms-donation
    networks:
      - donaton-network
    depends_on:
      donation-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://donation-db:5432/donation-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  ms-inventory:
    build: ./backend/ms-inventory
    container_name: ms-inventory
    networks:
      - donaton-network
    depends_on:
      inventory-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-db:5432/inventory-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  ms-logistic:
    build: ./backend/ms-logistic
    container_name: ms-logistic
    networks:
      - donaton-network
    depends_on:
      logistic-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://logistic-db:5432/logistic-db
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - donaton-network
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  profile-db:
    image: postgres:16
    container_name: profile-db
    environment:
      - POSTGRES_DB=profile-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - donaton-network
    volumes:
      - profile-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d profile-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  donation-db:
    image: postgres:16
    container_name: donation-db
    environment:
      - POSTGRES_DB=donation-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - donaton-network
    volumes:
      - donation-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d donation-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    environment:
      - POSTGRES_DB=inventory-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - donaton-network
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d inventory-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  logistic-db:
    image: postgres:16
    container_name: logistic-db
    environment:
      - POSTGRES_DB=logistic-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - donaton-network
    volumes:
      - logistic-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d logistic-db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  donaton-network:
    driver: bridge

volumes:
  auth-db-data:
  profile-db-data:
  donation-db-data:
  inventory-db-data:
  logistic-db-data: