apiVersion: v1
kind: Secret
metadata:
  name: donaton-global-secrets
type: Opaque
stringData:
  DB_USER: "user"
  DB_PASSWORD: "password"
  JWT_PRIVATE_KEY: "tu_llave_privada_aqui"
  JWT_PUBLIC_KEY: "tu_llave_publica_aqui"