apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-inventory
  template:
    metadata:
      labels:
        app: ms-inventory
    spec:
      initContainers:
        - name: wait-for-inventory-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - "until pg_isready -h inventory-db -p 5432 -U user; do echo esperando por inventory-db; sleep 2; done;"
      containers:
        - name: ms-inventory
          image: proyecto-fullstack-3-ms-inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://inventory-db:5432/inventory-db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: donaton-global-secrets
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: donaton-global-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ms-inventory-service
spec:
  selector:
    app: ms-inventory
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
