apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff-app
          image: proyecto-fullstack-3-bff:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICES_AUTH_URL
              value: "http://ms-auth-service:8081"
            - name: SERVICES_PROFILE_URL
              value: "http://ms-profile-service:8082"
            - name: SERVICES_DONATIONS_URL
              value: "http://ms-donation-service:8083"
            - name: SERVICES_INVENTORY_URL
              value: "http://ms-inventory-service:8084"
            - name: SERVICES_LOGISTIC_URL
              value: "http://ms-logistic-service:8085"
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: donaton-global-secrets
                  key: JWT_PUBLIC_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080