spring.application.name=donaton-bff
server.port=8080

# URLs internas de los microservicios (con puertos distintos para que no choquen en LEVANTAMIENTO LOCAL)
services.auth.url=http://localhost:8081
services.profile.url=http://localhost:8082
services.donations.url=http://localhost:8083
services.inventory.url=http://localhost:8084
services.logistic.url=http://localhost:8085

# Configuración de seguridad
jwt.public-key=${JWT_PUBLIC_KEY}