spring.application.name=donaton-bff
server.port=8080

services.auth.url=http://ms-auth:8081
services.profile.url=http://ms-profile:8082
services.donations.url=http://ms-donation:8083
services.inventory.url=http://ms-inventory:8084
services.logistic.url=http://ms-logistic:8085

# Configuración de seguridad
jwt.public-key=${JWT_PUBLIC_KEY}

# OpenAPI Configuracion
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

server.tomcat.max-http-response-header-size=16384

# Glitchtip
sentry.dsn=https://cdd28d829d8643b9a1309db346df5d33@app.glitchtip.com/25291

# En desarrollo 1 está bien, en producción 0.05 o 0.1 es recomendable
sentry.traces-sample-rate=1.0